In [ ]:
! conda install matplotlib
! conda install numpy
! conda install tifffile
! conda install PIL

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.widgets  import RectangleSelector
import tifffile as tiff
from PIL import Image
import pims
import os

In [2]:
%matplotlib notebook

In [3]:
datas_path_dir = 'C:/Users/1/Desktop/workspace/datas'
datas_list = os.listdir(datas_path_dir)
print(datas_list)

['cropped_datas', 'finished_datas', 'original_datas', 'results']


In [4]:
os.startfile(datas_path_dir+'/'+datas_list[2])

In [5]:
original_path = datas_path_dir+'/'+datas_list[2]
cropped_path = datas_path_dir+'/'+datas_list[0]
finished_path = datas_path_dir+'/'+datas_list[1]
result_path = datas_path_dir+'/'+datas_list[3]

print(f'original_path:{original_path} cropped_path:{cropped_path} finished_path:{finished_path} result_path:{result_path} ')

original_path:C:/Users/1/Desktop/workspace/datas/original_datas cropped_path:C:/Users/1/Desktop/workspace/datas/cropped_datas finished_path:C:/Users/1/Desktop/workspace/datas/finished_datas result_path:C:/Users/1/Desktop/workspace/datas/results 


In [6]:
original_datas_list = os.listdir(original_path)
print(original_datas_list)

['50fps_capsi_trap_230104_sample1 (2) (1).tif', '50fps_capsi_trap_230104_sample1 (2).tif', '50fps_capsi_trap_230104_sample1 (3) (1).tif', '50fps_capsi_trap_230104_sample1 (4) (1).tif', '50fps_capsi_trap_230104_sample1 (5).tif', '50fps_capsi_trap_230104_sample2 (1) (1).tif', '50fps_capsi_trap_230104_sample2 (2).tif', '50fps_capsi_trap_230104_sample2 (3) (1).tif', '50fps_capsi_trap_230104_sample2 (4).tif', '50fps_capsi_trap_230104_sample2 (5) (1).tif', '50fps_capsi_trap_230104_sample3 (1).tif', '50fps_capsi_trap_230104_sample3 (2).tif', '50fps_capsi_trap_230104_sample3 (3).tif', '50fps_capsi_trap_230104_sample3 (4) (1).tif', '50fps_capsi_trap_230104_sample3 (5) (1).tif', '50fps_capsi_trap_230104_sample3 (5).tif']


In [7]:
print(original_path+'/'+original_datas_list[0])

C:/Users/1/Desktop/workspace/datas/original_datas/50fps_capsi_trap_230104_sample1 (2) (1).tif


In [8]:
x_range = [0,0]
y_range = [0,0]

img = tiff.imread(original_path+'/'+original_datas_list[0])
img_array = np.array(img)

fig, ax = plt.subplots()
imgs = ax.imshow(img_array[:][0], cmap = 'gray')

<IPython.core.display.Javascript object>

In [9]:
def line_select_callback(eclick, erelease):
    'eclick and erelease are the press and release events'
    x1, y1 = eclick.xdata, eclick.ydata
    x2, y2 = erelease.xdata, erelease.ydata
    print("(%3.2f, %3.2f) --> (%3.2f, %3.2f)" % (x1, y1, x2, y2))
    print(" The button you used were: %s %s" % (eclick.button, erelease.button))

    global x_range
    global y_range

    x_range = [x1,x2]
    y_range = [y1,y2]

In [10]:
rs = RectangleSelector(ax, line_select_callback,
                       useblit=False, button=[1,3],
                       minspanx=5, minspany=5, spancoords='pixels',
                       interactive=True)

In [11]:
plt.show()

crop_img_array = img_array[:][0][int(y_range[0]):int(y_range[1]),int(x_range[0]):int(x_range[1])]

In [12]:
fig, ax = plt.subplots(frameon=False)
ax.axis('off')
imgs = ax.imshow(crop_img_array , cmap = 'gray')

plt.show()

<IPython.core.display.Javascript object>

In [ ]:
for i in range(len(img_array[:])):
    crop_img_array = img_array[:][i][int(y_range[0]):int(y_range[1]),int(x_range[0]):int(x_range[1])]
    fig, ax = plt.subplots(frameon=False)
    ax.axis('off')
    imgs = ax.imshow(crop_img_array, cmap='gray')
    plt.savefig(cropped_path+'/cropped_'+str(i)+'_'+original_datas_list[0]+'.tif', bbox_inches="tight", pad_inches = 0)


In [22]:
nd_array_stack = np.array([[[]]])

In [13]:
for i in range(len(img_array[:])):
    crop_img_array = img_array[:][i][int(y_range[0]):int(y_range[1]),int(x_range[0]):int(x_range[1])]
    print(crop_img_array.shape)
    print(crop_img_array)

(145, 155)
[[22567 19446 22607 ... 55898 53988 55268]
 [21240 18623 23343 ... 57210 55789 57089]
 [19046 18102 23303 ... 57313 56343 57012]
 ...
 [28488 28440 30198 ... 17091 16254 15947]
 [28122 27822 29427 ... 17408 15978 14783]
 [27747 27582 28766 ... 17773 16570 14796]]
(145, 155)
[[21496 18559 23011 ... 55564 54136 54487]
 [20649 18880 23637 ... 56953 55089 55581]
 [18086 17767 23268 ... 57091 56340 56901]
 ...
 [28993 28474 30021 ... 17126 16290 15444]
 [27943 27464 29892 ... 17227 16231 14891]
 [27641 27294 29198 ... 18096 16316 14115]]
(145, 155)
[[22199 18743 22717 ... 55713 54026 54451]
 [20832 18140 22679 ... 55837 54868 55953]
 [18381 17509 22858 ... 58016 56451 56122]
 ...
 [29244 28871 29660 ... 17199 16074 14869]
 [28085 27391 29393 ... 17623 15687 14313]
 [27926 27366 28303 ... 18672 16316 14758]]
(145, 155)
[[22088 18817 22532 ... 55115 54134 54786]
 [20760 18142 21797 ... 56135 54757 55215]
 [17977 17032 22639 ... 56089 54643 56197]
 ...
 [28704 28367 30057 ... 17018 

In [14]:
for i in range(len(img_array[:])):
    crop_img_array = img_array[:][i][int(y_range[0]):int(y_range[1]),int(x_range[0]):int(x_range[1])]
    #print(crop_img_array.shape)
    if i == 0:
        nd_array_stack = np.array([crop_img_array])
    else:
        nd_array_stack = np.concatenate((nd_array_stack,[crop_img_array]),axis=0)

print(nd_array_stack.shape)
print(nd_array_stack)


(500, 145, 155)
[[[22567 19446 22607 ... 55898 53988 55268]
  [21240 18623 23343 ... 57210 55789 57089]
  [19046 18102 23303 ... 57313 56343 57012]
  ...
  [28488 28440 30198 ... 17091 16254 15947]
  [28122 27822 29427 ... 17408 15978 14783]
  [27747 27582 28766 ... 17773 16570 14796]]

 [[21496 18559 23011 ... 55564 54136 54487]
  [20649 18880 23637 ... 56953 55089 55581]
  [18086 17767 23268 ... 57091 56340 56901]
  ...
  [28993 28474 30021 ... 17126 16290 15444]
  [27943 27464 29892 ... 17227 16231 14891]
  [27641 27294 29198 ... 18096 16316 14115]]

 [[22199 18743 22717 ... 55713 54026 54451]
  [20832 18140 22679 ... 55837 54868 55953]
  [18381 17509 22858 ... 58016 56451 56122]
  ...
  [29244 28871 29660 ... 17199 16074 14869]
  [28085 27391 29393 ... 17623 15687 14313]
  [27926 27366 28303 ... 18672 16316 14758]]

 ...

 [[24743 22360 23752 ... 62128 64939 65535]
  [23903 21425 24191 ... 60597 62653 65535]
  [21623 20096 25043 ... 59166 62698 65535]
  ...
  [33197 34321 36322 ...

In [15]:
converted_data =  nd_array_stack
print(nd_array_stack)
tiff.imwrite(cropped_path+'/'+'cropped'+original_datas_list[0], converted_data, photometric='minisblack')

[[[22567 19446 22607 ... 55898 53988 55268]
  [21240 18623 23343 ... 57210 55789 57089]
  [19046 18102 23303 ... 57313 56343 57012]
  ...
  [28488 28440 30198 ... 17091 16254 15947]
  [28122 27822 29427 ... 17408 15978 14783]
  [27747 27582 28766 ... 17773 16570 14796]]

 [[21496 18559 23011 ... 55564 54136 54487]
  [20649 18880 23637 ... 56953 55089 55581]
  [18086 17767 23268 ... 57091 56340 56901]
  ...
  [28993 28474 30021 ... 17126 16290 15444]
  [27943 27464 29892 ... 17227 16231 14891]
  [27641 27294 29198 ... 18096 16316 14115]]

 [[22199 18743 22717 ... 55713 54026 54451]
  [20832 18140 22679 ... 55837 54868 55953]
  [18381 17509 22858 ... 58016 56451 56122]
  ...
  [29244 28871 29660 ... 17199 16074 14869]
  [28085 27391 29393 ... 17623 15687 14313]
  [27926 27366 28303 ... 18672 16316 14758]]

 ...

 [[24743 22360 23752 ... 62128 64939 65535]
  [23903 21425 24191 ... 60597 62653 65535]
  [21623 20096 25043 ... 59166 62698 65535]
  ...
  [33197 34321 36322 ... 17880 16183 152

In [ ]:
cropped_path

In [32]:
x_range = [0,0]
y_range = [0,0]

img = tiff.imread('temp.tif')
img_array = np.array(img)

fig, ax = plt.subplots()
imgs = ax.imshow(img_array[:][0], cmap = 'gray')

<IPython.core.display.Javascript object>